apiVersion: v1
replicaCount: 2
namespace: default
metaLabels:
  - name: domain
    value: tools
ingress:
  name: kubelens-web-ingress
  host: kubelens.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
configMap:
  mountPath: "/mnt/config"
image:
  repository: docker.io/kubelens/kubelens-web
  tag: latest
  pullPolicy: Always
service:
  type: NodePort
  enableTLS: false
  port: 80
  containerPort: 39000
  annotations:
    app.kubernetes.io/name: kubelens-web
    app.kubernetes.io/instance: kubelens-web
    app.kubernetes.io/version: latest
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
resources:
  requests:
    cpu: 125m
    memory: 128M
  limits:
    cpu: 250m
    memory: 1G 
